{% set name = "ecp-cookie-init" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecp-cookie-init-{{ version }}.tar.gz
  sha256: fe7d364aab1f857b57ab10e84ef494e799a01d24e64734bff7a67de4e94969e7

build:
  number: 1
  noarch: python
  entry_points:
    - ecp-cookie-init = ecp_cookie_init:ecp_cookie_init
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    # automagic manpage generation
    - argparse-manpage
    - ciecplib
  run:
    - ciecplib
    - python >={{ python_min }}

test:
  imports:
    - ecp_cookie_init
    - ecp_cookie_init.tests
  commands:
    - pip check
    - python -m pytest --pyargs ecp_cookie_init
    - ecp-cookie-init --help
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://wiki.ligo.org/AuthProject
  summary: Utility for obtaining short-lived cookies for accessing Shibbolized SPs from command-line tools (e.g., curl or git)
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - duncanmmacleod
